export const DEFAULT_ROLE_GROUPS = [
  {
    label: '🎓 Carreira Acadêmica',
    options: [
      'Iniciação Científica (IC)',
      'Mestrando',
      'Doutorando',
      'Pós-Doutorando',
      'Pesquisador',
      'Pesquisador Sênior',
      'Professor Substituto / Temporário',
      'Professor Assistente',
      'Professor Adjunto',
      'Professor Associado',
      'Professor Titular',
      'Coordenador de Curso',
      'Chefe de Departamento',
    ],
  },
  {
    label: '💻 Engenharia de Software / Tecnologia (Técnico)',
    options: [
      'Engenheiro de Software Júnior',
      'Engenheiro de Software Pleno',
      'Engenheiro de Software Sênior',
      'Engenheiro de Software Especialista / Staff',
      'Engenheiro de Software Principal / Principal Engineer',
      'Engenheiro de Plataforma / Platform Engineer',
      'Engenheiro de Infraestrutura / DevOps / SRE',
      'Engenheiro de Segurança (AppSec / InfoSec)',
      'Engenheiro de Dados',
      'Engenheiro de Machine Learning (MLE)',
      'Arquiteto de Software',
      'Arquiteto de Soluções',
      'Arquiteto de Dados',
    ],
  },
  {
    label: '💻 Engenharia de Software / Tecnologia (Liderança)',
    options: [
      'Líder Técnico (Tech Lead)',
      'Engineering Manager',
      'Head de Engenharia',
      'Diretor de Engenharia',
      'VP de Engenharia',
      'CTO (Diretor Técnico)',
    ],
  },
  {
    label: '🔬 Ciência de Dados / IA / Pesquisa Aplicada',
    options: [
      'Analista de Dados',
      'Cientista de Dados Júnior',
      'Cientista de Dados Pleno',
      'Cientista de Dados Sênior',
      'Especialista em IA / ML',
      'Pesquisador em IA (Research Scientist)',
      'Pesquisador Aplicado (Applied Scientist)',
      'Engenheiro de IA (AI Engineer)',
      'Analista de BI / Business Intelligence',
      'Analista Quant / Quantitativo',
    ],
  },
  {
    label: '⚙️ Engenharia (Técnico — outras áreas)',
    options: [
      'Engenheiro Trainee',
      'Engenheiro Júnior',
      'Engenheiro Pleno',
      'Engenheiro Sênior',
      'Engenheiro Especialista',
      'Engenheiro Consultor',
      'Pesquisador em Engenharia (P&D)',
    ],
  },
  {
    label: '⚙️ Engenharia (Liderança — outras áreas)',
    options: [
      'Líder Técnico (Tech Lead)',
      'Coordenador de Engenharia',
      'Gerente de Engenharia',
      'Gerente de P&D',
      'Head de Engenharia',
      'Diretor de Engenharia',
    ],
  },
  {
    label: '📦 Produto (Product Management)',
    options: [
      'Associate Product Manager (APM)',
      'Product Manager (PM)',
      'Product Manager Sênior',
      'Group Product Manager (GPM)',
      'Principal Product Manager',
      'Director of Product',
      'VP de Produto',
      'Chief Product Officer (CPO)',
      'Product Designer / UX Designer',
      'UX Researcher',
    ],
  },
  {
    label: '📊 Gestão / Projetos / Operações',
    options: [
      'Analista de Projetos',
      'Coordenador de Projetos',
      'Gerente de Projetos (GP)',
      'Gerente de Programa (PgM)',
      'Gerente de Portfólio',
      'PMO',
      'Scrum Master',
      'Product Owner (PO)',
      'Agile Coach',
      'Coordenador de Operações',
      'Gerente de Operações',
      'COO (Diretor de Operações)',
    ],
  },
  {
    label: '💼 Negócios / Estratégia / Finanças',
    options: [
      'Analista de Negócios',
      'Consultor de Negócios / Estratégia',
      'Consultor (Big Four / Boutique)',
      'Analista Financeiro',
      'Analista de Investimentos',
      'Analista Quant (Finanças)',
      'Trader / Operador de Mesa',
      'Gerente Financeiro',
      'CFO (Diretor Financeiro)',
      'Account Manager',
      'Customer Success Manager',
      'Gerente Comercial / de Vendas',
      'Business Development Manager',
    ],
  },
  {
    label: '🏛️ Setor Público / Forças Armadas / Carreira de Estado',
    options: [
      'Estagiário em Órgão Público',
      'Servidor Público (Concursado)',
      'Analista de Órgão Público',
      'Especialista de Órgão Público',
      'Auditor Fiscal',
      'Técnico em Regulação / Agência Reguladora',
      'Pesquisador de Instituto Público (ex: INPE, INPI, Fiocruz)',
      'Diplomata / Carreira de Estado',
      'Militar — Oficial',
      'Professor Militar'
    ],
  },
  {
    label: '🚀 Empreendedorismo / Startups',
    options: [
      'Fundador / Co-Fundador',
      'CEO (Diretor Executivo)',
      'CTO Fundador',
      'Sócio',
      'Empreendedor em Série',
      'Empreendedor em Residência (EIR)',
    ],
  },
  {
    label: '🔍 Consultoria / Autônomo / Freelancer',
    options: [
      'Consultor Autônomo (Tecnologia)',
      'Consultor Autônomo (Negócios / Estratégia)',
      'Consultor Autônomo (Dados / IA)',
      'Freelancer de Software',
      'Freelancer de Dados',
      'Freelancer Técnico (geral)',
      'Autônomo / Prestador de Serviços',
    ],
  },
  {
    label: '📚 Outros / Transição de Carreira',
    options: [
      'Estagiário',
      'Trainee',
      'Em transição de carreira',
      'Estudando / Preparando concurso',
      'Intercâmbio / Sabbatical',
      'Prefiro não informar',
      'Outro',
    ],
  },
];